# 用于靠近敌人 平A之后需要根据后续动作判断等待秒数
# 接 特殊攻击 的话 等待 1.2 秒
# 接 蓄力3A 的话 等待 0.2 秒
# 接 5A接4A 的话 等待 0.6 秒
operations:
  - op_name: "按键-移动-前-按下"
    data: [ ]
  - op_name: "等待秒数"
    data: [ "0." ]
  - op_name: "按键-闪避"
    data: [ ]
  - op_name: "等待秒数"
    data: [ "0.1" ]
  - op_name: "按键-普通攻击"
    data: [ ]
  - op_name: "按键-移动-前-松开"
    data: [ ]