name: 问题反馈-通用
description: 不知道选啥的时候选这个就对了
title: "[问题反馈] [通用] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## 前置须知
        
        请先将代码更新至最新版本尝试是否依然有问题。

        请先阅读以下文档，里面可能就有你想要的答案
        - [运行前须知](https://github.com/DoctorReid/ZenlessZoneZero-OneDragon/wiki#2-%E8%BF%90%E8%A1%8C%E5%89%8D%E9%A1%BB%E7%9F%A5)

  - type: markdown
    attributes:
      value: |
        ## 问题反馈

  - type: textarea
    attributes:
      label: "问题描述"
      description: "尽量具体地描述产生这个问题的场景，详细的上下文有助于理解问题产生的原因。"
      placeholder: |
        1. 运行 闪避助手
        2. 画面出现黄光未自动闪避
    validations:
      required: true

  - type: textarea
    attributes:
      label: "游戏截图"
      description: "提供游戏截图有助于更直观地理解问题。使用脚本按F11进行截图最佳，图片保存在 .debug/images/ 文件夹中"
      placeholder: "游戏截图"

  - type: textarea
    attributes:
      label: "运行日志"
      description: "提供日志可以有助于理解脚本运行情况，日志保存在 .log/log.txt 中"
      placeholder: "运行日志"

  - type: textarea
    attributes:
      label: "你的建议"
      description: "针对这个场景，你觉得合适的解决方案是"
      placeholder: "你的建议"
