handlers:
  - states: "[前台-妮可]"
    sub_states:
    - states: "[按键可用-终结技]"
      operations:
        - op_name: "按键-终结技"
          data: []
        - op_name: "等待秒数"
          data: [ "3" ]
    - states: "[按键可用-特殊攻击]"
      operations:
        - operation_template: "妮可-蓄力特殊攻击"
    - states: ""
      operations:
        - op_name: "按键-普通攻击"
          data: []
        - op_name: "等待秒数"
          data: [ "0.3" ]
