template_name: "站场模板-未识别角色"
description: "开场未识别到角色时使用 先平A不呆住"
handlers:
- states: "![前台-击破] & ![前台-强攻] & ![前台-支援] & ![前台-防护] & ![前台-异常]"
  operations:
    - op_name: "按键-普通攻击"
      data: []
    - op_name: "等待秒数"
      data: [ "0.3" ]