template_name: "连携模板-强攻"
handlers:
  - states: "[连携技-1-强攻]"
    operations:
      - op_name: "按键-连携技-左"
        data: []
      - op_name: "等待秒数"
        data: [ "0.5" ]
  - states: "[连携技-2-强攻]"
    operations:
      - op_name: "按键-连携技-右"
        data: []
      - op_name: "等待秒数"
        data: [ "0.5" ]
