template_name: "速切模板-莱卡恩"
handlers:
  - states: "[前台-莱卡恩]"
    sub_states:
    - states: "[按键可用-特殊攻击]"
      operations:
        - op_name: "按键-特殊攻击-按下"
          data: [ "0.5" ]
        - op_name: "等待秒数"
          data: [ "0.1" ]
        - op_name: "设置状态"
          data: [ "自定义-速切结束" ]
    - states: ""
      operations:
        - op_name: "按键-普通攻击"
          data: []
        - op_name: "等待秒数"
          data: [ "0.1" ]
        - op_name: "设置状态"
          data: [ "自定义-速切结束" ]
